#!/bin/sh
. "$(dirname -- "$0")/_/husky.sh"


set -e

err_handler () {
    [ $? -eq 0 ] && exit
    npm run format:fix
    echo "👉 Fixed formatting — push again!"
    exit 1
}

echo Running pre-push checks...
npm run check
trap err_handler EXIT
npm run format:check
